import React from 'react';
import AlertItem from './AlertItem';
import useSimulationStore from '../../../store/useSimulationStore';
import { useTranslation } from 'react-i18next';

import { formatTimeByMode } from '../../../utils/timeFormat';

/**
 * AlertsFeed Component
 * 
 * Displays the real-time (or playback) log of clinical alerts generated by the system.
 * It automatically filters out future alerts when the user is scrubbing backwards
 * on the timeline (Time-Travel / DVR mode).
 */
export default function AlertsFeed() {
    const { t } = useTranslation();
    const alerts = useSimulationStore((state) => state.alerts);
    const currentTimeIndex = useSimulationStore((state) => state.currentTimeIndex);
    const biogearsHistory = useSimulationStore((state) => state.biogearsHistory);
    const joinedExternally = useSimulationStore((state) => state.joinedExternally);
    const activeSimulationStartTime = useSimulationStore((state) => state.activeSimulationStartTime);
    
    // Filters alerts dynamically for Time-Travel / DVR mode.
    // If the user scrubs the timeline back to second 50, we hide all alerts that happened after second 50.
    const visibleAlerts = alerts.filter(alert => 
        alert.simulationIndex === undefined || alert.simulationIndex <= currentTimeIndex
    );

    /**
     * Formats the timestamp of an alert depending on the active simulation mode.
     * In Live/IoT mode, it uses the absolute real-world time.
     * In Batch/Playback mode, it calculates the relative simulation time (e.g. 01:25).
     */
    const formatSimulationTime = (alert) => {
        // If it's IoT/Live and we have the real timestamp from the backend, we use it directly!
        if (joinedExternally && alert.timestamp) {
            let dateObj;
            if (Array.isArray(alert.timestamp)) {
                const [y, m, d, h, min, sec, n] = alert.timestamp;
                dateObj = new Date(y, m - 1, d, h, min, sec, (n || 0) / 1000000);
            } else {
                dateObj = new Date(alert.timestamp);
            }
            if (!isNaN(dateObj.getTime())) {
                return dateObj.toLocaleTimeString('pt-PT', { hour12: false });
            }
        }

        let index = alert.simulationIndex !== undefined ? alert.simulationIndex : 0;
        let totalSeconds = index;
        if (biogearsHistory && biogearsHistory.length > index && index >= 0) {
            totalSeconds = biogearsHistory[index].timestamp;
        }
        return formatTimeByMode(totalSeconds, activeSimulationStartTime, joinedExternally);
    };

    // Renders the scrollable list of filtered alerts
    return (
        <div className="flex-1 overflow-y-auto pr-1 custom-scrollbar">
            {visibleAlerts.length === 0 ? (
                <p className="text-xs text-slate-500 mt-4 text-center font-mono">{t('dashboard.noActiveAlerts')}</p>
            ) : (
            visibleAlerts.map((alert, index) => {
                    // Support both local UI alerts (alert.rule.severity) and
                    // real backend alerts from WebSocket (alert.severity directly)
                    const rawSeverity = (alert.severity ?? alert.rule?.severity ?? 'INFO').toUpperCase();
                    const isResolved = rawSeverity === 'NORMAL' || alert.status?.toUpperCase() === 'RESOLVIDO';
                    const alertType = rawSeverity === 'CRITICO' || rawSeverity === 'CRITICAL' ? 'critical'
                        : rawSeverity === 'SUCCESS' ? 'success'
                        : (rawSeverity === 'INFO' || isResolved) ? 'info'
                        : 'warning';

                    let title = alert.ruleName || alert.systemName || t('dashboard.physiologicalAlert');
                    if (isResolved) {
                        title = `${title} (${t('dashboard.stabilized')})`;
                    } else if (rawSeverity === 'WARNING' && alert.ruleName) {
                        // Extracts "a estabilizar" from the localized string to append it nicely
                        title = t('history.events.ruleStabilizing', { ruleName: title });
                    }
                    const subtitle = alert.formattedValue 
                        ? alert.formattedValue 
                        : (alert.valueAtTrigger !== undefined ? String(alert.valueAtTrigger) : '');

                    return (
                        <AlertItem
                            key={index}
                            time={formatSimulationTime(alert)}
                            type={alertType}
                            title={title}
                            subtitle={subtitle}
                            link={alert.link}
                        />
                    );
                })
            )}
        </div>
    );
}
